name: cd

on:
  workflow_dispatch:
  push:
    tags: [ v-* ]

jobs:
  cd:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Run
      run: go test -bench .
